version: '3'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./.docker/db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_DATABASE:-app}
      MYSQL_USER: ${DB_USER:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-pass}
    ports:
      - ${DB_PORT:-3306}:3306

  php:
    build:
      context: ./.docker/php
      args:
        TIMEZONE: ${TIMEZONE:-Europe/Warsaw}
    volumes:
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./:/var/www/

  nginx:
    image: nginx:1.22-alpine
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
      - ./:/var/www/
    ports:
      - ${PORT:-8080}:80
